### ISSUE TITLE
同样的主板，i5 9600kf+蓝宝石rx590 + 博通免驱网卡  该保留或删除哪些东西呢？

### ISSUE THREAD

**Issue by eamonzzz** [MonkeySdkCom/EFI-MSI-Z390-Tomahawk#2]
同样的主板，i5 9600kf+蓝宝石rx590 + 博通免驱网卡  该保留或删除哪些东西呢？

**Comment by mmonkeys** [comment]
OpenCore的驱动都放在/EFI-OC/OC/Kexts/里面，其中AirportBrcmFixup.kext是无线网卡驱动，WhateverGreen.kext是显卡驱动，可以先试试。

**Comment by mmonkeys** [comment]
最新提交已添加AirportBrcmFixup无线网卡驱动

**Comment by eamonzzz** [comment]
> OpenCore的驱动都放在/EFI-OC/OC/Kexts/里面，其中AirportBrcmFixup.kext是无线网卡驱动，WhateverGreen.kext是显卡驱动，可以先试试。

OK  非常感谢

**Comment by eamonzzz** [comment]
这个efi 启动不了 如果可以，能请你帮忙看看吗？

**Comment by mmonkeys** [comment]
什么错误

**Comment by eamonzzz** [comment]
> 什么错误

卡在这里   maching deferred by iousbhosthiddevices

**Comment by eamonzzz** [comment]
> > 什么错误
> 
> 卡在这里 maching deferred by iousbhosthiddevices

然后就出现 禁行标志

**Comment by eamonzzz** [comment]
![image](https://user-images.githubusercontent.com/20869326/68990882-80107b80-0893-11ea-9b96-dee22cf62838.png)

**Comment by mmonkeys** [comment]
换clover试试

**Comment by yelanxin** [comment]
同样的主板，启动直接报不支持，30秒自动关机，求解决办法。cpu 9600k用的集显

**Comment by eamonzzz** [comment]
> 同样的主板，启动直接报不支持，30秒自动关机，求解决办法。cpu 9600k用的集显

我换了一个efi成功了，我也上传到了github。你试试看

**Comment by mmonkeys** [comment]
默认使用Opencore，需要先去看看《精解Opencore》这个教程，我现在这个kext和efi是对应我这台机器一个个精简过的，都是通过源代码自己编译，可能其他机器有兼容问题，建议先采用Clover引导试试，这2种引导我都尝试过安装macos15.1是没有问题的。
