### ISSUE TITLE
BIOS 怎么设置

### ISSUE THREAD

**Issue by arthurtop** [MonkeySdkCom/EFI-MSI-Z390-Tomahawk#4]
CFG Lock (MSR 0xE2 write protection) -> Disabled （必须，否则黑屏无法开机）

**Comment by eamonzzz** [comment]
![image](https://user-images.githubusercontent.com/20869326/72331685-8f753f00-36f3-11ea-9262-469e7f54a7d7.png)

**Comment by arthurtop** [comment]
主板找不到 CFG这个设置 MSI Z390i
